version: "3.9"

services:
  builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.build
    image: rooteame-builder
    container_name: rooteame-build
    volumes:
      - ../src:/build/src
      - ./out:/build/out
    command: bash -c "make && cp *.ko /build/out/ && echo '[+] Build complete — rooteame.ko in docker/out/'"

  test-victim:
    image: ubuntu:24.04
    container_name: rooteame-victim-1
    command: sleep infinity
    networks:
      - rooteame-net
    cap_add:
      - NET_ADMIN
    volumes:
      - ./out:/tmp/rootkit

  test-victim-2:
    image: ubuntu:24.04
    container_name: rooteame-victim-2
    command: sleep infinity
    networks:
      - rooteame-net
    volumes:
      - ./out:/tmp/rootkit

  test-c2:
    image: ubuntu:24.04
    container_name: rooteame-c2
    command: sleep infinity
    networks:
      - rooteame-net

networks:
  rooteame-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
